<!doctype html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>LingoNexa · Learn languages deeply</title><link rel="stylesheet" href="{{ asset('css/lingonexa.css') }}"></head>
<body>
<nav class="landing-nav"><span class="brand">LN</span><strong style="font-size:20px">LingoNexa</strong><div class="grow"></div><a class="btn ghost" href="{{ route('login') }}">Sign in</a><a class="btn" href="{{ route('register') }}">Start learning</a></nav>
<main class="landing">
<section class="landing-hero">
<div><span class="pill" style="background:#eef0ff;color:#5265e8">67 languages · A1–C2 · Web + Flutter</span><h1 style="font-size:clamp(42px,7vw,72px);line-height:.98;margin:18px 0;letter-spacing:-.055em">Learn deeply.<br>Speak naturally.</h1><p class="muted" style="font-size:18px;max-width:680px">A polished language-learning system that combines structured courses, textbook-style grammar, smart review, stories, speaking practice, modern learning labs, and account-based progress.</p><div style="display:flex;gap:10px;flex-wrap:wrap;margin-top:22px"><a class="btn" href="{{ route('register') }}">Create free account →</a><a class="btn secondary" href="{{ route('login') }}">I already have an account</a></div><div class="flag-cloud">@foreach($languages as $item)<span class="flag">{{ $item['flag'] }} {{ $item['nativeName'] }}</span>@endforeach</div></div>
<div class="showcase"><div class="phone"><div class="hero" style="padding:18px;border-radius:22px"><small>YOUR LEARNING PATH</small><h2 style="margin:7px 0">Continue your journey</h2><p>Grammar · speaking · stories · review</p></div><div style="height:14px"></div><div class="mini">🧠 <strong>Nexa Learning Labs</strong><br><small class="muted">Active recall · spaced review · fluency</small></div><div class="mini">📚 <strong>Textbook Grammar</strong><br><small class="muted">Full explanations with aligned examples</small></div><div class="mini">🎙️ <strong>Speaking & Shadowing</strong><br><small class="muted">Practice full phrases at natural rhythm</small></div></div></div>
</section>
<section style="margin-top:70px"><div class="section-title"><h2>One learning system, multiple modes</h2><p>Built for desktop browsers, mobile browsers, and the Flutter application.</p></div><div class="grid"><div class="card"><div class="emoji">📖</div><h3>Book-quality explanations</h3><p class="muted">Connected explanations instead of fragmented rule boxes.</p></div><div class="card"><div class="emoji">🧠</div><h3>Modern learning science</h3><p class="muted">Retrieval, spacing, interleaving, dictation, chunking, and error repair.</p></div><div class="card"><div class="emoji">☁️</div><h3>Account progress sync</h3><p class="muted">XP, level, goals, completed lessons, exams and skills follow each user.</p></div></div></section>
</main></body></html>
